apiVersion: v1
kind: Secret
metadata:
  name: kujua-time-secrets
  namespace: kujua-time
type: Opaque
stringData:
  JWT_ACCESS_SECRET: replace-me
  JWT_REFRESH_SECRET: replace-me
  MONGODB_URI: mongodb://mongodb:27017/kujua-time?replicaSet=rs0
  REDIS_URL: redis://redis:6379
